### ISSUE TITLE
1.20.1 

### ISSUE THREAD

**Issue by pizzav-xyz** [JavaJump3r/JJElytraSwap#11]
how could i modify the 1.20.1 version of this mod?

**Comment by JumperOnJava** [comment]
> how could i modify the 1.20.1 version of this mod?

Use 1.19 branch, its build works up to 1.20.1 (inclusive)
But you probably should change version in properties file

**Comment by pizzav-xyz** [comment]
> > how could i modify the 1.20.1 version of this mod?
> 
> Use 1.19 branch, its build works up to 1.20.1 (inclusive) But you probably should change version in properties file

how would i make this equip elytra and then equip chestplate right after to use a bug?

**Comment by JumperOnJava** [comment]
What do you mean?

**Comment by pizzav-xyz** [comment]
> What do you mean?
automaticly do this
https://github.com/JumperOnJava/JJElytraSwap/assets/103120356/2ea11e34-631a-43ca-8bbd-fe9cabfb5d6c

**Comment by JumperOnJava** [comment]
I'm not sure what do you mean by that. What I can see on video is either some weird game glitch I don't know about or server not responding, so it doesn't update player pose (that can happen even in singleplayer)

**Comment by pizzav-xyz** [comment]
> I'm not sure what do you mean by that. What I can see on video is either some weird game glitch I don't know about or server not responding, so it doesn't update player pose (that can happen even in singleplayer)

yeah i want to do the thing in the video automaticly

**Comment by JumperOnJava** [comment]
Then I cannot help you. It is not this mod's purpose

**Comment by pizzav-xyz** [comment]
> Then I cannot help you. It is not this mod's purpose

how do i modify this mod to serve this purpose?

**Comment by JumperOnJava** [comment]
Would be easier to write a new mod as my mod doesn't change elytra mechanics (it just swaps two items when specific conditions met)

Also there are different ways to implement (for using it in singleplayer/on your server/on someone's else's server)

**Comment by pizzav-xyz** [comment]
> Would be easier to write a new mod as my mod doesn't change elytra mechanics (it just swaps two items when specific conditions met)
> 
> Also there are different ways to implement (for using it in singleplayer/on your server/on someone's else's server)

what different ways to implement
