### ISSUE TITLE
The mode file is called "JJElytraSwap-2.01 (2)"...

### ISSUE THREAD

**Issue by Ikiroux** [JavaJump3r/JJElytraSwap#14]
The mode file is called "JJElytraSwap-2.01 (2)" instead of "JJElytraSwap-2.01".

**Comment by JumperOnJava** [comment]
Bro why do you even care, just throw it to /mods and froget about it 😭

**Comment by Ikiroux** [comment]
Why don't just fix it bro ?? 😭
