### ISSUE TITLE
chat messages

### ISSUE THREAD

**Issue by oyou1234** [JavaJump3r/JJElytraSwap#17]
im not sure why but each time it equips my chestplate it sends a really annoying message that reads: 8 2.0 Diamond Chestplate. How do I even turn that off?? Needs to be fixed

**Comment by JumperOnJava** [comment]
What version of mod do you have
It is bug on 1.21 2.0, it is fixed on 1.21 2.01

**Comment by JumperOnJava** [comment]
Uhh forgot to close
