### ISSUE TITLE
when using the mod, it auto-equips chestplates in your inventory... 

### ISSUE THREAD

**Issue by itsMarkiS** [JavaJump3r/JJElytraSwap#2]
so if youre trying to enchant, rename or whatever else... you wont be able it will automatically be equiped

**Comment by somebirby** [comment]
This is the only downside of this mod.
Please allow for manually taking out the item in the chest slot by the player

**Comment by itsMarkiS** [comment]
YES! i hate this so much... i cant even rename my armor lol

**Comment by JumperOnJava** [comment]
fixed
