### ISSUE TITLE
[BUG]hotkey and Back to the original look

### ISSUE THREAD

**Issue by surfishs** [JavaJump3r/JJElytraSwap#4]
You should set a hotkey to disable this feature.
And I think it's silly to force chest armor on for players who aren't wearing it, it causes unnecessary trouble, for example a player wants to show his original skin, but the mod will keep trying to put on the clothes in his backpack for him.
As well, if I use aerial switch sheath wings without armor, when I land I should go back to not wearing armor instead of picking a piece of clothing I have stored in my backpack and putting it on.

**Comment by JumperOnJava** [comment]
ok so i added keybind. But i don't wand add "back to original look" feature beause there will be many different cases like what to do when player joined game with elytra, what mod should place into chestplate slot. Or what i should mod do if item disappeared. Should it wear best possible armor or not wear it at all. How we can determine best possible armor? There is too many cases when this feature may be broken while i'm trying to keep this mod as simple as possible

**Comment by surfishs** [comment]
> ok so i added keybind. But i don't wand add "back to original look" feature beause there will be many different cases like what to do when player joined game with elytra, what mod should place into chestplate slot. Or what i should mod do if item disappeared. Should it wear best possible armor or not wear it at all. How we can determine best possible armor? There is too many cases when this feature may be broken while i'm trying to keep this mod as simple as possible

You make a good point.
