### ISSUE TITLE
[Feature Request] Config for a delay to swap

### ISSUE THREAD

**Issue by Poke5555** [JavaJump3r/JJElytraSwap#7]
Would it be possible to add a configurable delay to to equipting the chestplate to allow for bouncing on the floor? or making so it stays with the elytra if your still holding space? [this](https://www.youtube.com/watch?v=1Yt1zNkXo5M) is an example of what i would like to be achievable but with the chestplate instantly equipting it makes it basically impossible. with a mod like [this](https://modrinth.com/mod/elytra-recast) it makes elytra very useful without fireforks
i really enjoy the mod :D

**Comment by JumperOnJava** [comment]
So i added compatibility with elytra recast
If recast is enabled chestplate will not be swapped on ground if space is pressed

**Comment by Poke5555** [comment]
It works flawlessy, thank you so much!
