### ISSUE TITLE
Prevent curse of binding chestplates from being automatically equipped

### ISSUE THREAD

**Issue by msfjarvis** [JavaJump3r/JJElytraSwap#8]
It is not uncommon to find an occasional curse of binding chestplate in loot chests and since the mod does not try to sort chestplates like it does elytras, it often results in the wrong chestplate being put on.

Just today I had to use cactus to fully break a diamond curse of binding chestplate which the mod applied on me while I was end busting.

**Comment by JumperOnJava** [comment]
lmao
i will fix this on weekend, should not be hard

**Comment by msfjarvis** [comment]
The code seemed intuitive enough so I took a crack at it, the changes in #9 fix the bug on my end.

**Comment by JumperOnJava** [comment]
pr merged, thanks for contributing
